name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Verify build
        run: |
          echo "Struktura dist:"
          ls -R dist
          
          echo "Sprawdzam główne pliki:"
          if [ -f "dist/index.html" ] && [ -f "dist/assets/main.js" ]; then
            echo "✅ Budowa udana!"
          else
            echo "❌ Brak plików budowy!"
            exit 1
          fi

      - name: Add routing files
        run: |
          cp public/404.html dist/ || echo "Brak 404.html"
          echo "www.modu.energy" > dist/CNAME
          touch dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: www.modu.energy
