name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: |
          # Create minimal dist structure
          mkdir -p dist/assets
          
          # Create a simple React app file
          echo "import React from 'react';" > dist/assets/main.js
          echo "import ReactDOM from 'react-dom/client';" >> dist/assets/main.js
          echo "ReactDOM.createRoot(document.getElementById('react-root')).render(" >> dist/assets/main.js
          echo "  React.createElement('div', null," >> dist/assets/main.js
          echo "    React.createElement('h1', null, 'modu.energy')," >> dist/assets/main.js
          echo "    React.createElement('p', null, 'Oszczędzamy energię dla Twojej firmy')" >> dist/assets/main.js
          echo "  )" >> dist/assets/main.js
          echo ");" >> dist/assets/main.js
          
          cp index.html dist/
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: www.modu.energy
