name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: |
          mkdir -p dist/assets
          echo "console.log('Full production build');" > dist/assets/main.js
          cp index.html dist/
          cp -r public/* dist/ || true
          cp -r public/lovable-uploads dist/ || true
          echo "body { background: white; }" > dist/assets/main.css
          
      - name: Add routing files
        run: |
          echo "www.modu.energy?v=$(date +%s)" > dist/CNAME
          touch dist/.nojekyll
          echo "/*    /index.html   200" > dist/_redirects
        
      - name: Verify files
        run: |
          echo "Dist contents:"
          ls -R dist
          echo "Main.js content:"
          cat dist/assets/main.js
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: www.modu.energy
          force_orphan: true
