name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Fix MIME types
      run: |
        # Add explicit .js extensions to all JS files
        find dist -type f -exec sed -i 's|"type":"module"|"type":"application/javascript"|g' {} \;
        
        # Add Content-Type headers
        echo -e "/*.js\n  Content-Type: application/javascript\n" > dist/_headers
        echo -e "/*.css\n  Content-Type: text/css\n" >> dist/_headers
        
    - name: Add SPA redirect
      run: echo "/*    /index.html   200" > dist/_redirects
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        destination_dir: /
        keep_files: false
        force_orphan: true
